#ifndef QTFLIGHTVIEW_GLOBAL_H
#define QTFLIGHTVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTFLIGHTVIEW_LIBRARY)
#  define QTFLIGHTVIEWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTFLIGHTVIEWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTFLIGHTVIEW_GLOBAL_H
