#ifndef RC_HANDLER_GLOBAL_H
#define RC_HANDLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RC_HANDLER_LIBRARY)
#  define RC_HANDLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RC_HANDLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RC_HANDLER_GLOBAL_H
