#ifndef STREAMMODE_HANDLER_GLOBAL_H
#define STREAMMODE_HANDLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STREAMMODE_HANDLER_LIBRARY)
#  define STREAMMODE_HANDLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STREAMMODE_HANDLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STREAMMODE_HANDLER_GLOBAL_H
